extraction:
  cpp:
    index: # Builds the project
      build_command: "python3 setup.py build_ext --inplace --headless --bullet"
    prepare:
      packages: # required apt-get packages
        - libbullet-dev
        - libegl1-mesa-dev
        - libglm-dev
        - libgl1-mesa-glx
        - libjpeg-dev
        - mesa-utils
  python:
    index: #don't scan notebooks
      exclude: examples/tutorials/nb_python/
    python_setup:
      version: "3"
path_classifiers:
  docs:
    - "docs"
  library:
    - "src/deps"
  tests:
    - "tests"
queries: # remove useless alerts
  exclude: py/import-and-import-from
